# Generated by Django 3.0.4 on 2020-04-01 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heads', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=255)),
                ('expenses_details', models.CharField(max_length=255)),
                ('receviable', models.CharField(max_length=255)),
                ('payment', models.CharField(max_length=255)),
            ],
        ),
    ]
