# Generated by Django 3.0.4 on 2020-04-09 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heads', models.CharField(choices=[('Salary', 'Salary'), ('Fee Collection', 'Fee Collection'), ('Current Bill', 'Current Bill'), ('Telephone Bills', 'Telephone Bills'), ('Misllanious', 'Misllanious'), ('Rent', 'Rent'), ('Transportation', 'Transportation'), ('Capitals', 'Capitals'), ('Loans', 'Loans'), ('Advances', 'Advances')], max_length=255)),
                ('date', models.DateField(blank=True, null=True)),
                ('expenses_details', models.CharField(max_length=255)),
                ('receviable', models.FloatField(default=0.0)),
                ('payment', models.FloatField(default=0.0)),
                ('date_year', models.IntegerField(default=0)),
                ('date_month', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
