# Generated by Django 3.0.4 on 2020-04-01 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_headcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='heads',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='school.HeadCategory'),
            preserve_default=False,
        ),
    ]
