# Generated by Django 3.0.4 on 2020-04-01 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_profile_heads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='heads',
            field=models.CharField(choices=[('Published', 'Published'), ('Pending Review', 'Pending Review'), ('Draft', 'Draft')], max_length=50),
        ),
        migrations.DeleteModel(
            name='HeadCategory',
        ),
    ]
