# Generated by Django 3.0.4 on 2020-04-03 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_auto_20200401_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='receviable',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='heads',
            field=models.CharField(choices=[('Salary', 'Salary'), ('Fee Collection', 'Fee Collection'), ('Current Bill', 'Current Bill'), ('Telephone Bills', 'Telephone Bills'), ('Misllanious', 'Misllanious'), ('Rent', 'Rent'), ('Transportation', 'Transportation'), ('Capitals', 'Capitals'), ('Loans', 'Loans'), ('Advances', 'Advances')], max_length=50),
        ),
    ]
