# Generated by Django 3.0.4 on 2020-04-03 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_auto_20200403_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='payment',
            field=models.FloatField(default=0.0),
        ),
    ]
