# Generated by Django 3.0.4 on 2020-04-03 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_auto_20200403_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='heads',
            field=models.CharField(choices=[('Salary', 'Salary'), ('Fee Collection', 'Fee Collection'), ('Current Bill', 'Current Bill'), ('Telephone Bills', 'Telephone Bills'), ('Misllanious', 'Misllanious'), ('Rent', 'Rent'), ('Transportation', 'Transportation'), ('Capitals', 'Capitals'), ('Loans', 'Loans'), ('Advances', 'Advances')], max_length=255),
        ),
    ]
