# Generated by Django 3.0.4 on 2020-04-04 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0011_auto_20200403_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
