# Generated by Django 3.0.4 on 2020-04-08 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0012_auto_20200404_0911'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
